version: '3'
services:
  ##Backend
  backend:
    build: 
      context: ./Backend/
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./Backend/src:/app
    ports:
      - 8000:50051
    command: sh -c "python3 app.py"
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./Backend/mysql/data:/var/lib/mysql
    - ./Backend/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./Backend/mysql/sql:/docker-entrypoint-initdb.d
    - ./Backend/mysql/csv:/etc/mysql/csv
    ports:
    - 3306:3306
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
     - ./frontend/react-sample/src:/usr/src/app/react-sample/src
    command: sh -c "npm install && npm start"
    ports:
     - "3000:3000"
    tty: true
  proxy:
    build: ./proxy
    command: "/usr/local/bin/envoy -c /etc/envoy/envoy.yaml"
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
  apigw:
    build:
      context: kong/kong/
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000 http2, 0.0.0.0:8443 ssl http2
    ports:
      - 80:8000
      - 8001:8001
      - 443:8443
      #- 9080:9080
      # - 8444:8444
    logging:
      options:
        max-size: "2g"
        max-file: "2"
  cassandra:
    build:
      context: kong/cassandra/
      dockerfile: Dockerfile
    # ports:
    #   - 9042:9042
    #volumes:
    #  - kong/Data:/var/lib/cassandra
    environment:
      JVM_OPTS: -Xms256M -Xmx256M
    logging:
      options:
        max-size: "1g"
        max-file: "2"
networks:
  default:
    driver: bridge