# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csample.proto\x12\x06sample\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x14TemparatureComponent\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x18\n\x10high_temperature\x18\x02 \x01(\x01\x12\r\n\x05place\x18\x03 \x01(\t\"\x14\n\x12TemparatureRequest\"F\n\x10TemparatureReply\x12\x32\n\x0ctemparatures\x18\x01 \x03(\x0b\x32\x1c.sample.TemparatureComponent2R\n\x07Greeter\x12G\n\x11ReturnTemparature\x12\x16.google.protobuf.Empty\x1a\x18.sample.TemparatureReply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_TEMPARATURECOMPONENT = _descriptor.Descriptor(
  name='TemparatureComponent',
  full_name='sample.TemparatureComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='sample.TemparatureComponent.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high_temperature', full_name='sample.TemparatureComponent.high_temperature', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='place', full_name='sample.TemparatureComponent.place', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=130,
)


_TEMPARATUREREQUEST = _descriptor.Descriptor(
  name='TemparatureRequest',
  full_name='sample.TemparatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=152,
)


_TEMPARATUREREPLY = _descriptor.Descriptor(
  name='TemparatureReply',
  full_name='sample.TemparatureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temparatures', full_name='sample.TemparatureReply.temparatures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=224,
)

_TEMPARATUREREPLY.fields_by_name['temparatures'].message_type = _TEMPARATURECOMPONENT
DESCRIPTOR.message_types_by_name['TemparatureComponent'] = _TEMPARATURECOMPONENT
DESCRIPTOR.message_types_by_name['TemparatureRequest'] = _TEMPARATUREREQUEST
DESCRIPTOR.message_types_by_name['TemparatureReply'] = _TEMPARATUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemparatureComponent = _reflection.GeneratedProtocolMessageType('TemparatureComponent', (_message.Message,), {
  'DESCRIPTOR' : _TEMPARATURECOMPONENT,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.TemparatureComponent)
  })
_sym_db.RegisterMessage(TemparatureComponent)

TemparatureRequest = _reflection.GeneratedProtocolMessageType('TemparatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPARATUREREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.TemparatureRequest)
  })
_sym_db.RegisterMessage(TemparatureRequest)

TemparatureReply = _reflection.GeneratedProtocolMessageType('TemparatureReply', (_message.Message,), {
  'DESCRIPTOR' : _TEMPARATUREREPLY,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.TemparatureReply)
  })
_sym_db.RegisterMessage(TemparatureReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='sample.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=226,
  serialized_end=308,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReturnTemparature',
    full_name='sample.Greeter.ReturnTemparature',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TEMPARATUREREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
